language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.22"
  - "5.20"
sudo: false
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --always-upgrade-modules
  - build-perl
  - perl -V
install:
  - cpan-install XML::LibXML Image::ExifTool
  - cpan-install --coverage
script:
  - ./picasa2xmp.pl --help | grep Usage
  - ./picasa2xmp.pl --man | grep SYNOPSIS
